### ISSUE TITLE
AssertionError: ./data/entity.dict does not exist!

### ISSUE THREAD

**Issue by dahuzi008** [XinyuHua/xref-chinese-el#1]
数据文件中缺少entity.dict文件~
python train.py --domain=ent\   
    --ckpt-dir=model/demo/ \
    --batch-size=32 \
    --model=xref \
    --tensorboard-dir=demo \
    --save-interval=1 \
    --save-topk=5 \
    --max-train-epochs=10

Traceback (most recent call last):
  File "train.py", line 80, in <module>
    main()
  File "train.py", line 53, in main
    model = model_class(args)
  File "/home/pc/disk_2T/pc/jupyter/dahuzi666/XREF/xref-chinese-el-master/models/xref.py", line 14, in __init__
    super().__init__(hparams)
  File "/home/pc/disk_2T/pc/jupyter/dahuzi666/XREF/xref-chinese-el-master/models/model.py", line 22, in __init__
    self.entity_dict = Vocab(dict_path=hparams.ent_vocab_path)
  File "/home/pc/disk_2T/pc/jupyter/dahuzi666/XREF/xref-chinese-el-master/vocab.py", line 7, in __init__
    assert os.path.exists(dict_path), f"{dict_path} does not exist!"
AssertionError: ./data/entity.dict does not exist!

**Comment by XinyuHua** [comment]
Thanks for pointing that out. I've updated the link to data, now it should contain entity.dict
